### ISSUE TITLE
AWS Amplify icon is missing

### ISSUE THREAD

**Issue by renebrandel** [boyney123/awsicons#1]
Hi - first off, I LOVE THIS tool.

I do miss the AWS Amplify logo though. 
![image](https://user-images.githubusercontent.com/4989523/100490555-18f5eb80-30d1-11eb-816d-f030399d1f5d.png)

**Comment by boyney123** [comment]
Not sure how that's missed, let me check :)

**Comment by boyney123** [comment]
@renebrandel do you have an SVG copy of it?

**Comment by renebrandel** [comment]
I don't have the exact SVG copy of it but I do have the logo available from docs.amplify.aws.
[Amplify Logo.svg.zip](https://github.com/boyney123/awsicons/files/5611296/Amplify.Logo.svg.zip)

**Comment by boyney123** [comment]
Thanks @renebrandel all sorted!

Converted it all to a svg and added it to the website. Thanks for raising the issue!

**Comment by renebrandel** [comment]
Thanks!! Love the tool!
