### ISSUE TITLE
Container services are duplicated

### ISSUE THREAD

**Issue by eddiezane** [boyney123/awsicons#3]
The container services are also present under the compute services causing them to appear twice in search.

https://github.com/boyney123/awsicons/tree/master/src/icons/Arch_Containers/32
https://github.com/boyney123/awsicons/tree/master/src/icons/Arch_Compute/32

Can probably remove them from compute?

**Comment by boyney123** [comment]
Hey @eddiezane,

Thanks didn't notice this! Removed a few duplicates. Thanks!
