### ISSUE TITLE
SVG versions?

### ISSUE THREAD

**Issue by onassar** [boyney123/awsicons#4]
Hi there -
Do you have these icons available as vector/SVG files?

**Comment by boyney123** [comment]
Hey @onassar 

Most of them are from https://aws.amazon.com/architecture/icons/

They have most icons you will need, I just created a platform to search through them.

Hope that helps?

**Comment by onassar** [comment]
What's your platform URL? 🐙

**Comment by boyney123** [comment]
No problem @onassar , enjoy!

**Comment by ykanavalik** [comment]
@boyney123 

Your service is much easier to navigate through, rather than AWS provided folder with bulky names. Don't you want to add a download SVG function?
